metadata.format.version = "1.1"

[versions]

velocity = "3.5.0-SNAPSHOT"
paper = "1.21.11-R0.1-SNAPSHOT"

runtask = "3.1.0"
pluginyml = "0.6.0"
shadow = "9.6.1"
blossom = "2.2.0"

brigadier = "1.0.500"
adventure = "5.0.0"
configurate = "4.2.0"
miniplaceholders = "3.1.0"

desertwell = "2.0.4"

guice = "7.0.0"
slf4j = "2.0.18"

[libraries]

velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

configurate = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }
miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniplaceholders" }

adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimesssage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
adventure-configurate = { group = "net.kyori", name = "adventure-serializer-configurate4", version.ref = "adventure" }

brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }

guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
desertwell = { group = "net.william278", name = "DesertWell", version.ref = "desertwell" }

plugin-shadow = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }

[plugins]

pluginyml = { id = "net.minecrell.plugin-yml.paper", version.ref = "pluginyml" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runtask" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.4.1" }
